project:
  type: website
  output-dir: _site

website:
  title: "GNSS Notes"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Notes
      - href: about.qmd
        text: About
  page-footer:
    left: "© IP-Solutions"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    link-external-newwindow: true

execute:
  freeze: auto
